name: Deploy only the Sherlock pages to gh-pages branch
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-roamlinks-plugin mkdocs-backlinks
      - run: mkdocs gh-deploy --force
